sudo: required
services:
  - docker

before_install:
  - docker build -t cromulentscientist/fib-eb -f ./client/Dockerfile.dev ./client

script:
  - docker run cromulentscientist/fib-eb npm test -- --coverage

after_success:
  - docker build -t cromulentscientist/fib-client ./client
  - docker build -t cromulentscientist/fib-nginx ./nginx
  - docker build -t cromulentscientist/fib-server ./server
  - docker build -t cromulentscientist/fib-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cromulentscientist/fib-client
  - docker push cromulentscientist/fib-nginx
  - docker push cromulentscientist/fib-server
  - docker push cromulentscientist/fib-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "fibonacci-managed"
  env: "FibonacciManaged-env"
  bucket_name: "elasticbeanstalk-us-west-2-004190587247"
  bucket_path: "fibonacci-managed"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY